import type {
  BusinessTypeConfig,
  InvoiceTemplateConfig,
  SectionKey,
} from "@/types/invoice-template";

export const SECTION_LABELS: Record<SectionKey, string> = {
  header: "Header",
  company_details: "Company details",
  client_details: "Client details",
  items: "Items",
  service_items: "Service items",
  tax: "Tax",
  discount: "Discount",
  payment_info: "Payment info",
  notes: "Notes",
  footer: "Footer",
};

export const BUSINESS_TYPES: BusinessTypeConfig[] = [
  {
    id: "retail",
    label: "Retail Shop",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "discount",
      "payment_info",
      "footer",
    ],
  },
  {
    id: "freelancer",
    label: "Freelancer / Service",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "service_items",
      "payment_info",
      "notes",
      "footer",
    ],
  },
  {
    id: "agency",
    label: "Agency",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "service_items",
      "tax",
      "payment_info",
      "notes",
      "footer",
    ],
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "discount",
      "payment_info",
      "notes",
      "footer",
    ],
  },
  {
    id: "gst",
    label: "GST Registered Business",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "discount",
      "payment_info",
      "notes",
      "footer",
    ],
  },
  {
    id: "other",
    label: "Other",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "payment_info",
      "notes",
      "footer",
    ],
  },
];

export const TEMPLATE_CATALOG: InvoiceTemplateConfig[] = [
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean grid layout with quiet typography.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#2563eb",
      fontFamily: "var(--font-geist-sans)",
      tableStyle: "minimal",
    },
  },
  {
    id: "modern",
    name: "Modern",
    description: "Gradient accents with bold totals.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "discount",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#0f766e",
      fontFamily: "var(--font-sora)",
      tableStyle: "modern",
    },
  },
  {
    id: "professional",
    name: "Professional",
    description: "Structured for enterprise clients.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#1f2937",
      fontFamily: "var(--font-geist-mono)",
      tableStyle: "grid",
    },
  },
  {
    id: "retail",
    name: "Retail",
    description: "Balanced table and POS friendly totals.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "discount",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#b45309",
      fontFamily: "var(--font-fraunces)",
      tableStyle: "minimal",
    },
  },
  {
    id: "compact",
    name: "Compact",
    description: "Slim spacing for quick billing flows.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#4338ca",
      fontFamily: "var(--font-geist-sans)",
      tableStyle: "minimal",
    },
  },
  {
    id: "slate",
    name: "Slate",
    description: "Muted tones with sharp dividers.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#0f172a",
      fontFamily: "var(--font-geist-mono)",
      tableStyle: "grid",
    },
  },
  {
    id: "apex",
    name: "Apex",
    description: "Crisp layout with premium contrast.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "discount",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#7c2d12",
      fontFamily: "var(--font-fraunces)",
      tableStyle: "modern",
    },
  },
  {
    id: "receipt",
    name: "Receipt",
    description: "Compact POS layout for faster billing.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "items",
      "tax",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#0f766e",
      fontFamily: "var(--font-geist-sans)",
      tableStyle: "minimal",
    },
  },
  {
    id: "luxe",
    name: "Luxe",
    description: "Elegant spacing for high-end services.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "service_items",
      "tax",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#4c1d95",
      fontFamily: "var(--font-sora)",
      tableStyle: "modern",
    },
  },
  {
    id: "studio",
    name: "Studio",
    description: "Creative layout with summary highlights.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "service_items",
      "discount",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#0e7490",
      fontFamily: "var(--font-geist-sans)",
      tableStyle: "modern",
    },
  },
  {
    id: "ledgerline",
    name: "Ledgerline",
    description: "Editorial spacing with confident totals.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#1f2937",
      fontFamily: "var(--font-geist-sans)",
      tableStyle: "grid",
    },
  },
  {
    id: "atlas",
    name: "Atlas",
    description: "Balanced columns for global accounts.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "discount",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#0f766e",
      fontFamily: "var(--font-sora)",
      tableStyle: "modern",
    },
  },
  {
    id: "harbor",
    name: "Harbor",
    description: "Calm layout for service studios.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "service_items",
      "tax",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#1d4ed8",
      fontFamily: "var(--font-geist-sans)",
      tableStyle: "minimal",
    },
  },
  {
    id: "verity",
    name: "Verity",
    description: "Clear hierarchy with minimal chrome.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#111827",
      fontFamily: "var(--font-geist-mono)",
      tableStyle: "grid",
    },
  },
  {
    id: "kite",
    name: "Kite",
    description: "Lightweight editorial tone for startups.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "discount",
      "payment_info",
      "footer",
    ],
    theme: {
      primaryColor: "#7c3aed",
      fontFamily: "var(--font-geist-sans)",
      tableStyle: "minimal",
    },
  },
  {
    id: "cascade",
    name: "Cascade",
    description: "Editorial rhythm for long service lists.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "service_items",
      "tax",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#0f172a",
      fontFamily: "var(--font-fraunces)",
      tableStyle: "modern",
    },
  },
  {
    id: "civic",
    name: "Civic",
    description: "Trustworthy grid for enterprise billing.",
    layout: "stacked",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "items",
      "tax",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#0c4a6e",
      fontFamily: "var(--font-geist-mono)",
      tableStyle: "grid",
    },
  },
  {
    id: "monarch",
    name: "Monarch",
    description: "Polished editorial look for premium clients.",
    layout: "split",
    defaultSections: [
      "header",
      "company_details",
      "client_details",
      "service_items",
      "discount",
      "payment_info",
      "notes",
      "footer",
    ],
    theme: {
      primaryColor: "#7c2d12",
      fontFamily: "var(--font-sora)",
      tableStyle: "modern",
    },
  },
];
